// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return apple;
      case TargetPlatform.macOS:
        return apple;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase registers a single "ios" app per bundle id that covers both iOS
  // and macOS, so both targets resolve to these same options.
  static const FirebaseOptions apple = FirebaseOptions(
    apiKey: 'AIzaSyDt5HkXXlSNNbjN8pOhSYZXFtBnuB4utY4',
    appId: '1:1040483089154:ios:b1e7c0d5cbdcdfae79201b',
    messagingSenderId: '1040483089154',
    projectId: 'test-96eab',
    storageBucket: 'test-96eab.firebasestorage.app',
    iosBundleId: 'com.workshopops.workshopOps',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbZ_pse2nQToy1w8O3NcOcI9i7q-Ve540',
    appId: '1:1040483089154:android:35c9c06cf2b8a61179201b',
    messagingSenderId: '1040483089154',
    projectId: 'test-96eab',
    storageBucket: 'test-96eab.firebasestorage.app',
  );
}
